import type { Metadata } from "next";
import "./globals.css";

import { Asap } from "next/font/google";

const asap = Asap({
  variable: "--font-asap",
  subsets: ["latin", "latin-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${asap.variable} antialiased`}>{children}</body>
    </html>
  );
}
